fixes for wislib

diff --git a/resources/wislib b/resources/wislib
--- a/resources/wislib
+++ b/resources/wislib
@@ -58,6 +58,10 @@ error () {
   fatal "$@"
 }
 
+warning-no-gui () {
+  echo Warning: Please install zenity or kdialog for graphical dialogs >&2
+}
+
 ask-file() {
   title="$1"
   dir="$2"
@@ -71,7 +75,11 @@ ask-file() {
   if [ -x `which zenity` ]; then
     zenity --fileselection --filename "$dir" --title "$title"
     return
-  fi 
+  fi
+  warning-no-gui
+  read -p "Filename:" file
+  echo "$file"
+  return
 }
 
 yesno () {
@@ -84,7 +92,12 @@ yesno () {
   if [ -x `which zenity` ]; then
     zenity --question --text "$QUESTION" --title "$TITLE"
     return $?
-  fi   
+  fi
+  warning-no-gui
+  read -p "$QUESTION [yn]" res
+  [ "$res" == "y" ] && return 0
+  [ "$res" == "n" ] && return 1
+  return 2
 }
 
 #-----------------------------------------
@@ -115,6 +128,12 @@ compare_version () {
   exit 0;" $1 $2
 }
 
+disallow_wine_version () {
+  VER="$1"
+  compare_version `wine_version` $VER
+  [ $? -lt 0 ] || fatal "Wine version $VER cannot be used"
+}
+
 require_min_wine_version () {
   MIN_VER="$1"
   compare_version `wine_version` $MIN_VER
@@ -134,25 +153,8 @@ require_min_wislib_version () {
 }
 
 #-----------------------------------------
-#------------- Other Stuff ---------------
+#------------- Wine Calls ----------------
 #-----------------------------------------
-
-download () {
-  URL="$1"
-  FILE="$2"
-  HASH="$3"
-  if [ -f "$FILE" ]; then
-    FHASH=`sha1sum $FILE | awk '{ print $1 }'`
-    if [ "$HASH" == "$FHASH" ]; then
-      return
-    else
-      rm "$FILE"
-    fi
-  fi
-  wget -nd -c "$URL" -O "$FILE" 
-  FHASH=`sha1sum $FILE | awk '{ print $1 }'`
-  [ "$HASH" == "$FHASH" ] || fatal "Hash value of $URL has changed (expected: $HASH, was $FHASH"
-}
 
 wine () {
   $WINE "$@"
@@ -202,6 +204,27 @@ override_app_dlls() {
   app="$1"
   shift
   int_override_dlls "HKEY_CURRENT_USER\\Software\\Wine\\AppDefaults\\$app\\DllOverrides" "$@"
+}
+
+#-----------------------------------------
+#------------- Other Stuff ---------------
+#-----------------------------------------
+
+download () {
+  URL="$1"
+  FILE="$2"
+  HASH="$3"
+  if [ -f "$FILE" ]; then
+    FHASH=`sha1sum $FILE | awk '{ print $1 }'`
+    if [ "$HASH" == "$FHASH" ]; then
+      return
+    else
+      rm "$FILE"
+    fi
+  fi
+  wget -nd -c "$URL" -O "$FILE" 
+  FHASH=`sha1sum $FILE | awk '{ print $1 }'`
+  [ "$HASH" == "$FHASH" ] || fatal "Hash value of $URL has changed (expected: $HASH, was $FHASH"
 }
 
 find_on_cd() {
